### ISSUE TITLE
适配 laravel 框架

### ISSUE THREAD

**Issue by zoulux** [go-microservices/php_conf_agent#4]
导出的配置文件不是 .php 文件，可以是一个 ini 格式的文件，类似与 laravel 的 env 配置文件

**Comment by GanymedeNil** [comment]
开发之初，就不打算做成配置文件而是作为php文件是因为可以直接调用，并且现在的方式在laravel中可以直接通过config方法调用

**Comment by zoulux** [comment]
所以你的想法是将 config 文件夹下面的所有 php 文件都配置到 Apollo作为 namespace 吗

**Comment by zoulux** [comment]
确实我现在也在发愁，共享卷怎么共享一个 env 文件，目前我也只能共享一个目录

**Comment by GanymedeNil** [comment]
> 所以你的想法是将 config 文件夹下面的所有 php 文件都配置到 Apollo作为 namespace 吗

目前来看是的
