### ISSUE TITLE
k8s 中 Deployment 如何做心跳检测

### ISSUE THREAD

**Issue by zoulux** [go-microservices/php_conf_agent#6]
livenessProbe 等该如何设计？
监听一个端口？
提供一个脚本？
@GanymedeNil  一起讨论讨论

**Comment by GanymedeNil** [comment]
作为一个配置文件同步的工具我个人认为可以不做心跳检测，但可以收集相关错误日志和Go相关指标来监测服务是否异常。还有就是需要关注Apollo这类基础服务以及业务侧的异常检测与报警机制。
